Added permanent command instructions
gadhagod/TerminalToDo pull request #1
Opened 2020-09-28 22:17 UTC by shaunikm

Now shows how to make the command permanent and how to "uninstall" the command

2020-09-28 23:44 UTC, gadhagod commented
Adding the alias to .bashrc should create a permanent alias. What OS are you using?

2020-09-29 00:55 UTC, shaunikm commented
mac OS Catalina 10.15.6 (10.15.7 is the latest). I've researched on the internet and I made the pull requests based on what I learned. I also made this pull requests because I've been using <code>ttd</code> and I had to keep doing
```
$ source ~/.bashrc
```
everytime I wanted to use the command. Since this is an inconvenience, I tried to find a solution and found that writing to .bash_profile makes it permanent. I tried it and it worked.

2020-09-29 00:58 UTC, gadhagod commented
But adding the alias to .bashrc didn't make it permanent? What exactly did you put in .bashrc?

2020-09-29 01:00 UTC, shaunikm commented
I put exactly what the tutorial said I should put:
```
alias ttd='python3 ~/TerminalToDo/ttd'
```
I also put this exact line into .bash_profile and only had to source .bash_profile once.

2020-09-29 01:03 UTC, gadhagod commented
Were you using the bash shell? If in the bash shell, the commands in .bashrc should execute without you needing to run them.

2020-09-29 01:05 UTC, shaunikm commented
Yes.

2020-09-29 01:15 UTC, gadhagod requested changes
.bashrc OR .bash_profile

2020-09-29 01:15 UTC, gadhagod commented
For me, adding the alias to .bashrc worked. Maybe in your README you could say:<br>
> add the alias to .bashrc. On some systems, you need to add the alias to .bash_profile, and run <code>source .bash_profile</code>
until I find out why your alias from .bashrc is not working. I will submit a code review right now.

2020-10-07 18:13 UTC, gadhagod requested changes

2020-10-07 18:13 UTC, gadhagod commented on README.md
> +The file may already have text written in it, but ignore it as it isn't important.
Unnecessary

2020-10-07 18:13 UTC, gadhagod commented on README.md
> +source ~/.bashrc
No point of adding to .bashrc if you need to run <code>source</code>.

2020-10-07 18:13 UTC, gadhagod commented on README.md
> +source ~/.bashrc
No point of adding to .bashrc if it's not permanent.

2020-10-07 18:13 UTC, gadhagod commented on README.md
> +nano ~/.bashrc
Remove this please

2020-10-07 18:13 UTC, gadhagod commented on README.md
> +At the end (or beginning of the file, write:
Replace with 
> append the following to the file

2020-10-07 18:13 UTC, gadhagod commented on README.md
> +<h3>Uninstallation</h3>
Uninstallation is a good thing to add to the README. However, just say to remove the alias and keep it short.

2020-10-10 00:56 UTC, gadhagod commented
It seems this pull request has been abandoned.

2020-10-10 00:56 UTC, closed without merging